public class MainClass {
   
    Fridge f = new Fridge();
    Fridge f1 = new Fridge('X2-00', 10);
    Fridge f2 = new Fridge();
   	
    public MainClass()
    {
        system.debug('Fridge object f');
    }
    //f2.setNumberInStock(20);
  /*  system.debug('Fridge object f');
    system.debug(f.getModelNumber(), f.getNumberInStock());
    system.debug('Fridge object f1');
    system.debug(f1.getModelNumber(), f1.getNumberInStock());
    system.debug('Fridge object f2');
    system.debug(f2.getModelNumber(), f2.getNumberInStock());*/
}